name: video_player_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  file_picker: ^8.3.1
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  get: ^4.7.2
  video_thumbnail: 
    git:
      url: https://github.com/Shahidbangash/video_thumbnail.git 
      ref: master 
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
